### ISSUE TITLE
missing distance and type attributes

### ISSUE THREAD

**Issue by vermeer47** [joe-akeem/contour-tiles#15]
Problem:
The generated contour.mbtiles is missing the distance and type attributes. It seems like the distance attribute is only added for the <type>_contour<20/100>.geojson files. Could it be that previously the contour.geojson files were generated using ogr2ogr by merging the contour20 and contour100 ones propagating the attributes, whilst now since gdal_contour is used the attributes are not generated? Both the readme and the style files are still referencing these attributes.

Potential Solution for distance attribute:
The distance attribute might be unnecessary as the mapbox gl style spec is supporting the modulo operator, such that 100m interval contours can be styled different from the 20m ones using an expression like this:
```
  "filter": [
    "==",
    ["%", ["get", "elev"], 100],
    0
  ], 
```

**Comment by joe-akeem** [comment]
Thanks for the proposal 🙏  I will try it out and update the documentation if it works!
