### ISSUE TITLE
Empty vector map preview 

### ISSUE THREAD

**Issue by necarnot** [joe-akeem/contour-tiles#20]
Hello,

Thank you for this work, so helpful. I followed the README and successfully created the mbtiles for switzerland.
In the osm directory, I can see the mbtiles are created, and I tried to import them into QGis and they did appear, which proves their creation was a success.

After that, I'm running docker compose up to launch klokantech's tileserver-gl, and the http://localhost:8080 does show the basic web page with the styles and data chapters.

In the data chapters, I can see the raster maps of slope and hillshades.
But in the first chapter, styles, I can click on "Vector" to see the map but I only get a blank map.
In this blank map, I can (pretend to) zoom, as I can see the URL changing. I can also rotate like in any vector map, but nothing but white map is showing.

In the docker compose logs, I see nothing happening.

I also tried to replace klokantek's tileserver-gl docker image with maptiler's one, as adviced on dockerhub, but to no avail and with the same result.

I see no error in my browsers dev tools logs (firefox and chromium).

**Comment by joe-akeem** [comment]
Hi,

thanks for reporting. I just fixed part of the problem. The resource for glyphs returned a `404` error. Now if you enter coordinates and a zoom level that lie within the area that you configured and a zoom level >=10, you should get the styled map. For example, for Switzerland this should work: http://localhost:8080/styles/contour/#10/46.665/7.8978

Why it doesn't automatically center around the data that it finds in the mbtiles file I haven't found out yet. For the inspection of the raw data it seems to work.

**Comment by necarnot** [comment]
Hi @joe-akeem , I confirm that you patch solves the issue the way you explained.
About the centering, I'll also work on my side to try to understand.

Thank you.

**Comment by joe-akeem** [comment]
@necarnot this issue is fixed now
