### ISSUE TITLE
contour.json is mising

### ISSUE THREAD

**Issue by webmap2015** [joe-akeem/contour-tiles#3]
Hi,

In the "tileserver-style.json" file, it says "line 11 url: mbtiles://contour.json"

After docker image builted, there is no contour.json file.

Thanks.

**Comment by joe-akeem** [comment]
Right, I think that it should say `contour.mbtiles`. I fixed that:
https://github.com/joe-akeem/contour-tiles/commit/131531dfdb77fd421534cf83763554889e7e11b1

Thanks for pointing it out @webmap2015 !
