### ISSUE TITLE
add a .dockerignore file

### ISSUE THREAD

**Issue by CramericaIndustries** [joe-akeem/contour-tiles#5]
Rebuilding of the image failed with a "not enough disk space" error message.
Reason was that docker included the already downloaded DEM data into the build context of the docker container. Adding a `.dockerignore` file to the root directory of the project solved that issue.
Content of the `.dockerignore` file:
```
osm/*
img/*
postgres-data/*
```

**Comment by joe-akeem** [comment]
I added a `.dockerignore` with the content above. Thanks for the feedback!
