### ISSUE TITLE
The United States?

### ISSUE THREAD

**Issue by swork1** [joe-akeem/contour-tiles#9]
I would like to be able to use the same process for the United States. What all would need changed in order to do that? Has anyone already done this?

**Comment by joe-akeem** [comment]
@swork1 unfortunately the container currently isn't generic enough that you could achieve this through configuration. For now I extended the README with a description how to modify the `Makefile` to achieve that, see https://github.com/joe-akeem/contour-tiles/pull/10 HTH!

**Comment by swork1** [comment]
> @swork1 unfortunately the container currently isn't generic enough that you could achieve this through configuration. For now I extended the README with a description how to modify the `Makefile` to achieve that, see #10 HTH!

Amazing! I'll give it a shot sometime soon
